/*
 * generated by Xtext
 */
package de.unistuttgart.iste.ps.skilled;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SKilLStandaloneSetup extends SKilLStandaloneSetupGenerated{

	public static void doSetup() {
		new SKilLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

