/*
 * generated by Xtext
 */
package de.unistuttgart.iste.ps.skilled;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SKilLRuntimeModule extends de.unistuttgart.iste.ps.skilled.AbstractSKilLRuntimeModule {
	 //
}
