/*
 * generated by Xtext
 */
package de.unistuttgart.iste.ps.skilled.ui.contentassist

import de.unistuttgart.iste.ps.skilled.ui.contentassist.AbstractSKilLProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SKilLProposalProvider extends AbstractSKilLProposalProvider {
}
