/*
 * generated by Xtext
 */
package de.unistuttgart.iste.ps.skilled.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SkillUiModule extends de.unistuttgart.iste.ps.skilled.ui.AbstractSkillUiModule {
	public SkillUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
